### ISSUE TITLE
Infos & quickstart wanted

### ISSUE THREAD

**Issue by jeansaigne** [florentpoujol/superpowers-dom-plugin#1]
Hello Florent,
First thank you for your plugin, it looks like what i'm looking for, but not sure yet: one of my goals is to  embed external videos, so does your plugin...:
- ...allow to manipulate DOM elements ?
- ...allow to embed iframes ?

Maybe if you provide a quickstart, it would be easier to understand the possibilities it gives.

It's been 4 month you didn't work on it so thank you by advance for the time taken answering.

**Comment by florentpoujol** [comment]
The plugin only exposes all the "javascript standard libraries" to Superpowers.
With it, you can do everything you can do with classic javascript.

So you can definitely manipulate DOM and create iframes.

This should work :

```
const document = window.document; // not sure it's needed

const frame = document.createElement("iframe");
frame.src = "http://what.ever";
frame.style.width =  "800px";
frame.style.height =  "600px"

document.body.appendChild(frame);
```

This will add the iframe after Sup's canvas, you probably need to use `position: absolute` CSS property to place it over it.

I currently don't have Superpowers installed right now so I can't test this particular code but you get the idea.
Note that Sup may have some protection against embedding things via iframe, I don't know.
